select KATUR.CUSTOMER.CUSTOMERID, KATUR.CUSTOMER.FNAME, KATUR.CUSTOMER.LNAME, KATUR.DOCUMENT.ISSUEDATE, KATUR.DOCUMENT.EXPIRYDATE 
from KATUR.DEPARTMENT join KATUR.DOCUMENT D on KATUR.DEPARTMENT.DEPTID = D.DEPTID
where 08-03-1990 = expirydate;
